/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cyjh_input_InputEventStub */

#ifndef _Included_com_cyjh_input_InputEventStub
#define _Included_com_cyjh_input_InputEventStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cyjh_input_InputEventStub
 * Method:    SetProtoType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_cyjh_input_InputEventStub_SetProtoType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cyjh_input_InputEventStub
 * Method:    WriteInitData
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_cyjh_input_InputEventStub_WriteInitData
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cyjh_input_InputEventStub
 * Method:    TouchDownEvent
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_cyjh_input_InputEventStub_TouchDownEvent
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_cyjh_input_InputEventStub
 * Method:    TouchMoveEvent
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_cyjh_input_InputEventStub_TouchMoveEvent
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_cyjh_input_InputEventStub
 * Method:    TouchUpEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_cyjh_input_InputEventStub_TouchUpEvent
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
